DELETE http://localhost:8080/product/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWRtaW4xQGFkbWluLmNvbSIsImV4cCI6MTcxNjA3NDExMCwiaWF0IjoxNzE2MDcwNTEwLCJzY29wZSI6IkFETUlOIE1FUkNIQU5UIFVTRVIifQ.kEAvp3D6BC__BoRNKguzqCydFGkL6ogyWyuwLPOKkXwapuR1_Z7QMPmI26xHAAWn0gRnHS9rdtsz1z04gQtalCdra6LFlUhgO0blqZF455CEhnTN0-Y30Pesy3l4jAfNzIznliQhtylei1nMeW7eaBVi2CFqugwhOOA-pAu6hXZri2KBN3byJoEo8qHictbUpbX0FFj4RdWHv-e8Q9lYqUiXOl7GN1oX916Zfq-BxvcqjDE10fq6GlcYNInLtBOKaKcU_grMF5qQNUcLETRCuW9mGs5XoppD-ZYIMdQqCpP63ojwO28xOVCSaYW8VG86kGzc97_UHXhNnJM9rCoA7w

{
    "productId": 14
}