GET http://localhost:8080/product/get-recommendations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiMTIzQG1zbi5jb20iLCJleHAiOjE3MTYzMTc0MjIsImlhdCI6MTcxNjMxMzgyMiwic2NvcGUiOiJNRVJDSEFOVCBVU0VSIn0.a4H0vmSjd-pcD4kUq7y8MidT7BsQYKfs3wDrMGmUVZxsHsiYM5JDiTWPHS9AKZ1GR-TsUrC1TbNvX2fG7pkEsxpv0IYPFEUla4QcAviuFLqsH33Kk00F6M1i_SBdKSTVkIIAHLUOQKvX8qg1FMYlTwP8a6Lb1Mfdyz4BJ7y9nEtAW9Bj8hRC6JhD7VnHbmd7EeCsivULjTlCp60_zeljDk8O1Lda1uAr53ivr5zpXxSrPjfxdOYObI4sQ4BM_6qR7fqtGogDk3nRfYUvow82v-k8SzqOLkGqzKMZqLeE5RlkNMyTY9yvZNd23GE7bfs35Y3uAvMW_I8Qhi0I3ZsMBw
