POST http://localhost:8080/admin/approve-all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWRtaW5AYWRtaW4uY29tIiwiZXhwIjoxNzE1NzI0MzMwLCJpYXQiOjE3MTU3MjA3MzAsInNjb3BlIjoiQURNSU4gTUVSQ0hBTlQgVVNFUiJ9.XXk0Vl28mTlyHPpDedYz6rAygXQL52olJF0S5bMvM1huPiZivlOaNp1G7mJTmv5LI_iMnfW1sKhLFZva8kXxvjedofUHDB2dsVJ-eiFsQT8MI8P-a38J9xmnCmSSi0F8Un8L1meptjLTsqtwRvly82ELqXfCRD67gkxoUz3-i4hjoNRXZthXh7T8YN6xo-T-Syo0UJBnXN1mERbGiEA7bwWcl1ONS4fuURidkMPn3ItkMXUN56QjM40o3toR4MNhor4JfBBvSXv4MWuQk_dL555Z5Bu5peYtwXIKa51CxEiYYjLHC0-pXxdU_S7lwebiLjTwwgbe-LbQ6ko0bo4ZXA