POST http://localhost:8080/admin/approve
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWRtaW5AYWRtaW4uY29tIiwiZXhwIjoxNzE1NzE4MjI2LCJpYXQiOjE3MTU3MTQ2MjYsInNjb3BlIjoiQURNSU4gTUVSQ0hBTlQgVVNFUiJ9.wDtVtNd7JMiry-UxspEYzyWbQpacxZFuInrMj4Ygi8ssDfQvqY6JmQPB6t7fuKh46s4jcFwcS3-cY6E3f7xH6IU_C9J-z5wbPFW8O4pCQ3_fvKi4gwKFzu0khHVUb68MzTS3ms7k1mR42xsB4K3F1RMOrMB_eefMjf41Pn103P3LC93Lm37juyhY_cIzpYgJrUovF0lfuBi_M_eppz0uYJXu3gLGyRMge7VgngVeTsFPDLyutHR3pAHgZz7eRu-yoXcry0RQd5mtdB7nYiqNUT1SMxavcmH-Jebww6W89HWNsE5C4w7Q91VQRK0zTMTFDGHnvZX0Es5DjuUlNEumgg

{
    "userId" : 15
}