POST  http://localhost:8080/admin/ban
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWRtaW4xQGFkbWluLmNvbSIsImV4cCI6MTcxNjA0MDM4NCwiaWF0IjoxNzE2MDM2Nzg0LCJzY29wZSI6IkFETUlOIE1FUkNIQU5UIFVTRVIifQ.raPeV75sNGfFEXQJB0fq6w7OurYFc7OzmeWToeEK-1dXJns3FJ1UU_5a8w98HEHj2u0OAuldeltccHBwwrPvfDGT61mN534fCmOjxzLX7-UVT5MgC99DeKKcSvYBb3jSubyYQ9A4Svau0PW3-FbmBn_BulsSMxY4o8Kt7xc7G9SBbiImxDB3XPRnk129MU34G4zTo70Vh4VBfb4Pq9ViKD8PSf790uShlqhnwPjQmYJ5M-PDQQAonGbW_b-u1nmbje8eYx9fu8XL0ZY9XyXzpsugJhmBcXYDH3uE7Hek4XGUFFzbywaAXthhJ4gY3hrnbeWgcFP-xwTep8wSMtiuVA

{
    "userId" : 5
}