GET http://localhost:8080/admin/pending-users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWRtaW4xQGFkbWluLmNvbSIsImV4cCI6MTcxNjE1MTQ0NCwiaWF0IjoxNzE2MTQ3ODQ0LCJzY29wZSI6IkFETUlOIE1FUkNIQU5UIFVTRVIifQ.bJZ7MqOGCle8Va7zEfkGgHNGlzRoi31VZQW8W_CcxYhLjPanYsQdpwoebyVVNozZrI_hdLB8_H8iWbGhuWkWH_qaNXtQ91VC9heA_B1rx6p0zYXrZMgcxIK6m7JbDXvxOb35jhK3G_6yRiTbW8BZQGe3dTe4X3MscJjWIvQW96xC2wGuk8kul-H3OmyZCzcb2HNV2ow1-RcOj9sO1ZuiJoDlpopGQBGMP_v7eZiSh2TVM6-Ooh7U5Ne_0QdUvBJ-y1nBjdKUmM2Av3PHMkEOBQAwo708GQ18nGvRBoyd_KN8Vo6Yh5675m2E_5uvsZeYVhvdC5E-43B-WBoEZQUZYw