POST http://localhost:8080/admin/reject-all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWRtaW5AYWRtaW4uY29tIiwiZXhwIjoxNzE1NzI0NjAxLCJpYXQiOjE3MTU3MjEwMDEsInNjb3BlIjoiQURNSU4gTUVSQ0hBTlQgVVNFUiJ9.DEZlW_4Yxd5CnvKEO-gKqjfRPwy4aHHkVHKFBEH2NqttwRmIsWppJs1WGtFkR447T_7U01r_zLDjUSiR7x91bsx0X-maVfZm0JBVlu4sgJKquiDpwZqWIBxW3JOfPxwSlcDcnwGbGBFj7lO81vCUNKMQBTMBDFfumkgcIdOefw1tf90Tu62AQVnJJaZWPNb7ktu_Azrw3dusLJQbGsnqsEnCsKrZkAnTXGnQmi-BPhTxP4Y5ZYFlwpV-iNKnRTXjs8J24T02a-AcfYKT7XBklUI7qXggYmDC17r6DUH9T7oLV3D5NzmylpCEsZ4trieh-rrEX3TaL1za-xZ4qqKQjA