POST http://localhost:8080/admin/reject
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWRtaW5AYWRtaW4uY29tIiwiZXhwIjoxNzE1NzIyMTk5LCJpYXQiOjE3MTU3MTg1OTksInNjb3BlIjoiQURNSU4gTUVSQ0hBTlQgVVNFUiJ9.WLBJxSh7s3yyeB3C0PKQgtb9F3sjbKHUQ_yKfngzIPrcQiN1rPFpmm7pnjP927gchppUqZu6Ve6v6ZodkbeQX790JsPKozp1m--G0PwaATt-kGLT3C60fjgtd3F81Nx3Y5uekEpn4S_6gKeIUK_udPrjRqWPQ780K0wtQrTgm3_kBuRU4rVZwAO9mAK4WPJ3Ra8pJUTwlFtj_kmfxkcT_Vpe0rOGDCLG4jYnAg0RHkDoX_wbR7m1BqAjKplz7RWpZOwaivH_3kU36MLk00NQjzEXnGfhBG2olppNcNPBdsiUE0TIffBcuMpZj_Hqr3_taXG-lcGDSUZd2rc0y780kA

{
    "userId" : 17
}