POST http://localhost:8080/user/whoami HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidGFtZXJ5ZXNpbGRhZzMyMUBnbWFpbC5jb20iLCJleHAiOjE3MTUxOTYzMzQsImlhdCI6MTcxNTE5MjczNCwic2NvcGUiOiJVU0VSIn0.rcMOAS9ALqSPLMCGkRpwlFyctuiTUMKSBmXbOlxMumi2qH1TBDy42MB6fwuS0HoJ_UX-xMAhqbu1LEegdLvfRKLPp2Caz8Kcxi5qIk3K12cVLzvwiv8VnpkXYY6KQ1t7vcLEkWZ5Fae5_95YVxvyb6WF425XkA3KTXVy4-Z-SEgkQjok_rsqbm2yKv8N9b49mViYDEUOSgNev4JIp3thg6GAAVzOOP0_7WwYz-09OWQqEvpU96xiOZNlZeYmlq7OyrFHed3VfDoMVmifYdhd-Kf0IpmbM9wyGPpoamNzffzuDQMlUM1qVBY__5n2R9Bp-0kAGAsP8DmuACPgsNAUaQ