DELETE http://localhost:8080/community/forum/delete-reply-post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWRtaW4xQGFkbWluLmNvbSIsImV4cCI6MTcxNTk2NTI3OCwiaWF0IjoxNzE1OTYxNjc4LCJzY29wZSI6IkFETUlOIE1FUkNIQU5UIFVTRVIifQ.Q6Cq29f9ZWLtGlHhHMZFfN_lb1sLrr8Uk3L-KvTfoP_6WAIIHS_7a09gKR88O-PvQ0MmlU9bulvhpBtl2S2o_pc3l-SlcASm46GYsWgZ4NnU8vY5BO7dpA8QCCCtkwxuc5GmacDR6_uiOCwbMtJ3J15r27US8M7m960c7WpC_nmKUtnT3Vn9ktgX6V48gWi7YQSt6XrLY-yd_iO1uLJ1iWN5fF7BL9uZQidQHw1idjC0JvSelTNa9Q2z7Ouuol40IDuM4Rx0X_8mIHFeGF7WS9X5MFHQbTMfA4TXFfP6dD2_EbF-_W5bJrs2oOXOsdfmgo3_FOYGCkfC6oGxndGm7Q

{
    "postId": 1
}